# Generated by Django 5.1.2 on 2024-11-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0003_remove_user_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')],
                                   default='pending', max_length=20),
        ),
    ]
