# Generated by Django 5.1.2 on 2024-11-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0002_property_city_alter_property_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
