# Generated by Django 5.1.2 on 2024-11-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='amenity/icons/'),
        ),
    ]
