# Generated by Django 5.1.2 on 2024-11-07 13:56

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0004_amenity_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id',
                 models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('review', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='comment', to='property.review')),
            ],
        ),
    ]
