# Generated by Django 5.1.2 on 2024-11-07 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='context',
            new_name='content',
        ),
    ]
