# Generated by Django 5.1.2 on 2024-11-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0007_review_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='verification',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')],
                                   default='pending', max_length=20),
        ),
    ]
