# Generated by Django 5.1.2 on 2024-11-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')],
                                   default='pending', max_length=255),
        ),
    ]
